#!/bin/bash
#!/apps/spack/root/opt/spack/linux-rhel9-haswell/gcc-13.2.0/r-4.5.1-264p7tzsobm57jhwvpte6ky7gzb45g7j/bin/Rscript

#SBATCH --time=01:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=8192M   # memory per CPU core


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

Rscript ProcessRNAData.R